---
name: Build Container

"on":
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64 binary
        run: cargo build --release

      - name: Install cross
        run: cargo install cross

      - name: Build aarch64 binary
        run: cross build --release --target aarch64-unknown-linux-gnu
